-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgZck/rvfukGfsRXw8
vSbC4JzF3zCdJUZuIG1jEcwvTHagCgYIKoZIzj0DAQehRANCAAQG8HLV7O1iP9H0
TnbapZl4Y3pXvLZK8XtX/gc4w+H/2bKPyiXsyz9YSuf+nWbeFwOyczmt1NO6XJxn
ORfnznGV
-----END PRIVATE KEY-----